# Generated by Django 2.2.14 on 2020-07-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test',
            new_name='sdf',
        ),
    ]
