# Generated by Django 2.2.14 on 2020-07-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200722_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sdf',
        ),
    ]
