# Generated by Django 2.2.14 on 2020-07-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_customtext_testfgwrtg"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="fgdhtyuhrtyuiluopqwewrqewefwr",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="hgfhgfhgfhgfhgfhgfsesws",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
