# Generated by Django 2.2.14 on 2020-07-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_auto_20200722_0724"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtext", name="fgdhtyuhrtyuiluopqwewrqewefwr",
        ),
        migrations.RemoveField(
            model_name="customtext", name="hgfhgfhgfhgfhgfhgfsesws",
        ),
    ]
