# Generated by Django 2.2.14 on 2020-07-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200722_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='user2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
